

  services:
    postgres-db:
      image: postgres:latest
      restart: always
      container_name: postgres_fakestore
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - ./postgres_data:/var/lib/postgresql/data